[versions]
agp = "8.7.2"
kotlin = "1.9.0"
coreKtx = "1.15.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
lifecycleRuntimeKtx = "2.8.7"
activityCompose = "1.9.3"
composeBom = "2024.04.01"

squareup_retrofit = "2.9.0"
squareup_logger = "5.0.0-alpha.3"

koin = "3.4.0"
serialization = "1.6.3"
androidx_navigation = "2.8.0-beta06"
credentials = "1.5.0-beta01"
facebookLogin = "latest.release"
firebase_bom = "33.1.2"
google-firebase-crashlytics-plugin = "3.0.2"
lifecycleProcess = "2.8.6"
mapsCompose = "6.1.0"
playServicesAuth = "21.2.0"
googleid = "1.1.1"
androidx_datastore = "1.1.1"
coil = "2.4.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }


##Retrofit
squareup_retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "squareup_retrofit" }
squareup_retrofit_gson_converter = { module = "com.squareup.retrofit2:converter-gson", version.ref = "squareup_retrofit" }
squareup_logger = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "squareup_logger" }

##Koin
koin_core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin_android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin_compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin" }

#Navigation
androidx_navigation = { module = "androidx.navigation:navigation-compose", version.ref = "androidx_navigation" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization"}


facebook-login = { module = "com.facebook.android:facebook-login", version.ref = "facebookLogin" }

firebase_bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebase_bom" }
firebase-messaging-ktx = { group = "com.google.firebase", name = "firebase-messaging" }
firebase-auth = { module = "com.google.firebase:firebase-auth" }

maps-compose = { module = "com.google.maps.android:maps-compose", version.ref = "mapsCompose" }
androidx-credentials-play-services-auth = { module = "androidx.credentials:credentials-play-services-auth", version.ref = "credentials" }
androidx-credentials = { module = "androidx.credentials:credentials", version.ref = "credentials" }
googleid = { group = "com.google.android.libraries.identity.googleid", name = "googleid", version.ref = "googleid" }


androidx_datastore = { module = "androidx.datastore:datastore-preferences", version.ref = "androidx_datastore" }

coil = { module = "io.coil-kt:coil", version.ref = "coil" }
coil_gif = { module = "io.coil-kt:coil-gif", version.ref = "coil" }
coil_compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

